os:
  - linux
  - osx
language: perl6
perl6:
  - 2017.05
install:
  - rakudobrew build zef
  - (for f in File::Temp Text::Markdown Template::Mustache YAMLish; do zef --verbose install $f; done)
script:
  - PERL6LIB=$PWD/lib prove -e perl6 -vr t/
sudo: false
